# Generated by Django 4.1.7 on 2023-03-25 18:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="apt_num",
            field=models.IntegerField(
                db_column="apt_num", default=1, verbose_name="Apartment Number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartment",
            name="square_meter",
            field=models.IntegerField(
                db_column="square_meter", default=1, verbose_name="Square Meter"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartment",
            name="street",
            field=models.CharField(
                db_column="street",
                default=1,
                max_length=128,
                validators=[django.core.validators.MinLengthValidator(5)],
                verbose_name="Street Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartment",
            name="street_num",
            field=models.IntegerField(
                db_column="street_num", default=1, verbose_name="Street Number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartment",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apartment",
            name="zip_code",
            field=models.CharField(
                db_column="zip_code",
                default=1,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Zip code must be 7 digits and match the pattern of an Israeli zip code.",
                        regex="^[0-9]{7}$",
                    )
                ],
                verbose_name="Zip Code",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=128)),
                ("description", models.TextField(db_column="description")),
                (
                    "price",
                    models.DecimalField(
                        db_column="price", decimal_places=0, max_digits=5
                    ),
                ),
                ("from_date", models.DateField(db_column="from_date")),
                ("to_date", models.DateField(db_column="to_date")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, db_column="duration", default=0, null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_column="is_active", default=False),
                ),
                (
                    "apt_id",
                    models.ForeignKey(
                        db_column="apt_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="api.apartment",
                    ),
                ),
            ],
        ),
    ]
