# Generated by Django 4.1.7 on 2023-03-25 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_apartment_apt_num_apartment_square_meter_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="listing",
            table="listings",
        ),
    ]
