# Generated by Django 4.1.7 on 2023-03-25 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_listing_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartment",
            old_name="user_id",
            new_name="user",
        ),
    ]
