# Generated by Django 4.1.7 on 2023-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="liked_apartments",
            field=models.ManyToManyField(
                default=None, through="api.LikedApartments", to="api.apartment"
            ),
        ),
    ]
