# Generated by Django 4.1.7 on 2023-03-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_userprofile_liked_apartments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="from_date",
            field=models.DateTimeField(db_column="from_date"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="to_date",
            field=models.DateTimeField(db_column="to_date"),
        ),
    ]
