# Generated by Django 4.1.7 on 2023-04-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_likedapartments_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="is_balcony",
            field=models.BooleanField(db_column="is_balcony", default=False),
        ),
        migrations.AddField(
            model_name="apartment",
            name="is_parking",
            field=models.BooleanField(db_column="is_parking", default=False),
        ),
        migrations.AddField(
            model_name="apartment",
            name="is_wifi",
            field=models.BooleanField(db_column="is_wifi", default=False),
        ),
        migrations.AddField(
            model_name="apartment",
            name="pet_friendly",
            field=models.BooleanField(db_column="pet_friendly", default=False),
        ),
        migrations.AddField(
            model_name="apartment",
            name="smoke_friendly",
            field=models.BooleanField(db_column="smoke_friendly", default=False),
        ),
        migrations.DeleteModel(
            name="Attribute",
        ),
    ]
