# Generated by Django 4.1.7 on 2023-04-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_apartment_is_balcony_apartment_is_parking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
