# Generated by Django 4.1.7 on 2023-04-01 17:45

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_review_created_review_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proposal",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="is_active",
            field=models.BooleanField(db_column="is_active", default=True),
        ),
    ]
