# Generated by Django 4.2 on 2023-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_apartmentphoto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_pic",
            field=models.URLField(default="Test", max_length=512),
            preserve_default=False,
        ),
    ]
