# Generated by Django 4.2 on 2023-05-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_userprofile_google_oauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="uuid",
            field=models.UUIDField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
