# Generated by Django 4.2 on 2023-05-18 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0021_apartment_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikedListings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.listing"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "liked_listings",
            },
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="liked_by_users",
        ),
        migrations.DeleteModel(
            name="LikedApartments",
        ),
        migrations.AddField(
            model_name="listing",
            name="liked_by_users",
            field=models.ManyToManyField(
                related_name="liked_listings",
                through="api.LikedListings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="likedlistings",
            constraint=models.UniqueConstraint(
                fields=("user", "listing"), name="unique_user_liked_listings"
            ),
        ),
    ]
